<a href="https://colab.research.google.com/github/Siddhartha0310/nlp_practicals/blob/main/kindle_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Kindle reveiw sentiment analysis

Data set from https://jmcauley.ucsd.edu/data/amazon/

Dataset has the follwing the xolumns
reviewerID - ID of the reviewer, e.g. A2SUAM1J3GNN3B
asin - ID of the product, e.g. 0000013714
reviewerName - name of the reviewer
helpful - helpfulness rating of the review, e.g. 2/3
reviewText - text of the review
overall - rating of the product
summary - summary of the review
unixReviewTime - time of the review (unix time)
reviewTime - time of the review (raw)

Best practices the will followed:-
preprocessing
Train test split
BOW,Tfidf,word2vec
train ml alogorithms

In [47]:
import pandas as pd
data=pd.read_csv("/content/all_kindle_review.csv")
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [48]:
data=data[['reviewText','rating']]
data

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       3
1      Great short read.  I didn't want to put it dow...       5
2      I'll start by saying this is the first of four...       3
3      Aggie is Angela Lansbury who carries pocketboo...       3
4      I did not expect this type of book to be in li...       4
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       4
11996  I have read all seven books in this series. Ap...       5
11997  This book really just wasn't my cuppa.  The si...       3
11998  tried to use it to charge my kindle, it didn't...       1
11999  Taking Instruction is a look into the often hi...       3

[12000 rows x 2 columns]

In [49]:
data.isna().sum()

reviewText    0
rating        0
dtype: int64

In [50]:
data['rating'].unique()

array([3, 5, 4, 2, 1])

In [51]:
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [52]:
#preprocessing and cleaning
data['rating']=data['rating'].apply(lambda x: 0 if x<3 else 1 )

In [53]:
data['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [54]:
## lower all the cases
data['reviewText']=data['reviewText'].str.lower()
data.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [55]:
!pip install beautifulsoup4 lxml

In [56]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [57]:
import re
from nltk.corpus import stopwords
from bs4 import BeautifulSoup

data['reviewText'] = data['reviewText'].apply(lambda x: re.sub(r'[^a-z0-9\s\-]', '', x))
stop_words = set(stopwords.words('english'))  # Use set for faster lookup
data['reviewText'] = data['reviewText'].apply(
    lambda x: " ".join(y for y in x.split() if y and y not in stop_words)
)
data['reviewText'] = data['reviewText'].apply(
    lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', str(x))
)
data['reviewText'] = data['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
data['reviewText'] = data['reviewText'].apply(lambda x: " ".join(x.split()))

In [58]:
data.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [61]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemtizer=WordNetLemmatizer()

def lemmatixe(text):
  return " ".join([lemtizer.lemmatize(word) for word in text.split()])


[nltk_data] Downloading package wordnet to /root/nltk_data...


In [62]:
data['reviewText']=data['reviewText'].apply(lambda x: lemmatixe(x))

In [63]:
data.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data['reviewText'], data['rating'], test_size=0.20, random_state=42)

In [78]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()


In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()


In [80]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow, y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tfidf, y_train)



In [85]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
y_pred_bow =nb_model_bow.predict(X_test_bow)
print('Bag of words confusion matrix:-',confusion_matrix(y_test,y_pred_bow))
print('Bag of words accuracy:-',accuracy_score(y_test,y_pred_bow))
print('Bag of words classifaction report:-',classification_report(y_test,y_pred_bow))

y_pred_tdif =nb_model_tfidf.predict(X_test_tfidf)
print(confusion_matrix(y_test,y_pred_tdif))
print(accuracy_score(y_test,y_pred_tdif))

Bag of words confusion matrix:- [[499 304]
 [717 880]]
Bag of words accuracy:- 0.5745833333333333
Bag of words classifaction report:-               precision    recall  f1-score   support

           0       0.41      0.62      0.49       803
           1       0.74      0.55      0.63      1597

    accuracy                           0.57      2400
   macro avg       0.58      0.59      0.56      2400
weighted avg       0.63      0.57      0.59      2400

[[488 315]
 [696 901]]
0.57875


Since precision is not good applying word2Vec

In [89]:
!pip install gensim
import nltk
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [90]:
import gensim
from gensim.models import Word2Vec,KeyedVectors
from nltk.tokenize import word_tokenize
data['reviewText']= data['reviewText'].apply(lambda x: word_tokenize(x))


In [94]:
model=gensim.models.Word2Vec(data['reviewText'],vector_size=100)

In [96]:
import numpy as np
def averageWord2Vec(doc):
  return np.mean([model.wv[word] for word in doc if word in model.wv],axis=0)

In [97]:
!pip install tqdm
from tqdm import tqdm

In [100]:
doc=[]
for i in tqdm(range(data['reviewText'].size)):
  doc.append(averageWord2Vec(data['reviewText'][i]))

100%|██████████| 12000/12000 [00:02<00:00, 5244.48it/s]


In [103]:
doc_new =np.array(doc)
doc_new

array([[-0.08490197,  0.19795497,  0.08085674, ..., -0.32896593,
         0.00650485, -0.20735876],
       [-0.09247258,  0.21892107, -0.14058127, ..., -0.15540752,
         0.00470221, -0.47611684],
       [-0.15833618,  0.23924065, -0.0834035 , ..., -0.2597845 ,
         0.05716152, -0.15071112],
       ...,
       [-0.09164461,  0.20478539, -0.05934098, ..., -0.096292  ,
        -0.08272742, -0.5036417 ],
       [ 0.22547454,  0.24065286,  0.12948146, ..., -0.5410484 ,
         0.04553423, -0.0931969 ],
       [-0.06921072,  0.19453846,  0.03717378, ..., -0.14190213,
        -0.03515773, -0.27438095]], dtype=float32)

In [108]:
from sklearn.model_selection import train_test_split
X_train_vec, X_test_vec, y_train_vec, y_test_vec = train_test_split(doc_new, data['rating'], test_size=0.20, random_state=42)

In [109]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_vec, y_train)


In [112]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
y_pred_vec =nb_model_bow.predict(X_test_vec)
print(confusion_matrix(y_test,y_pred_vec))
print(accuracy_score(y_test,y_pred_vec))
print(classification_report(y_test,y_pred_vec))


[[ 603  200]
 [ 453 1144]]
0.7279166666666667
              precision    recall  f1-score   support

           0       0.57      0.75      0.65       803
           1       0.85      0.72      0.78      1597

    accuracy                           0.73      2400
   macro avg       0.71      0.73      0.71      2400
weighted avg       0.76      0.73      0.73      2400



In [153]:
import os

# Retrieve the token from Colab's secrets manager
token = os.environ.get('GITHUB_TOKEN')

# Construct the remote URL with your username and token
remote_url = f"https://Siddhartha0310:{token}@github.com/Siddhartha0310/nlp_practicals.git"

# Update the remote origin URL
!git remote set-url origin "{remote_url}"

In [154]:
!git remote -v


origin	https://Siddhartha0310:None@github.com/Siddhartha0310/nlp_practicals.git (fetch)
origin	https://Siddhartha0310:None@github.com/Siddhartha0310/nlp_practicals.git (push)


In [155]:
!git add .


In [156]:
!git commit -m "Kindle_text_analysis"

On branch main
nothing to commit, working tree clean


In [159]:
# Push the committed changes to the remote repository using the constructed remote_url
!git push -u "{remote_url}" main

remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/Siddhartha0310/nlp_practicals.git/'
